random_quotes= {"quotes": {

    "motivational": [
  { "text": "Dreams grow only when watered with action.", "author": "Alex Carter" },
  { "text": "Progress is silent until success makes the noise.", "author": "Maya Sterling" },
  { "text": "The only real failure is refusing to try.", "author": "Jordan Blake" },
  { "text": "Great things begin with uncomfortable steps.", "author": "Lena Hayes" },
  { "text": "Your story isn’t over — it’s just turning the page.", "author": "Noah Rivers" },
  { "text": "Strength doesn’t shout; it shows up.", "author": "Ava Monroe" },
  { "text": "Every sunrise brings another chance to start again.", "author": "Eli Torres" },
  { "text": "If you can imagine it, you can become it.", "author": "Riley Grant" },
  { "text": "Little efforts build impossible dreams.", "author": "Sophia Lane" },
  { "text": "Hope is the engine of resilience.", "author": "Liam Cross" },
  { "text": "Discipline is the bridge between intention and achievement.", "author": "Harper Quinn" },
  { "text": "Courage grows when comfort ends.", "author": "Dylan West" },
  { "text": "You become unstoppable when purpose replaces fear.", "author": "Chloe Rivers" },
  { "text": "Even small steps forward are still progress.", "author": "Isaac Miller" },
  { "text": "Turn your wounds into wisdom, not walls.", "author": "Sienna Vale" },
  { "text": "The harder the climb, the better the view.", "author": "Logan Bryce" },
  { "text": "Effort beats talent when talent stops trying.", "author": "Olivia Park" },
  { "text": "Fall seven times, rise eight — every time stronger.", "author": "Evan Frost" },
  { "text": "Success begins with believing you can.", "author": "Aria Bloom" },
  { "text": "Don’t wait for inspiration — act, and it will follow.", "author": "Miles Rowan" },
  { "text": "Be the energy you want your goals to feel.", "author": "Isla King" },
  { "text": "Failure is not the opposite of success — it’s the foundation.", "author": "Kai Turner" },
  { "text": "Push past doubt — growth lives there.", "author": "Zoe Hart" },
  { "text": "Your potential expands with every challenge you face.", "author": "Caleb North" },
  { "text": "The grind today is the glory tomorrow.", "author": "Ivy Monroe" },
  { "text": "If it scares you, it’s probably worth doing.", "author": "Theo Reed" },
  { "text": "Persistence turns ordinary into extraordinary.", "author": "Nova Clarke" },
  { "text": "The dream is free — the hustle is sold separately.", "author": "Jace Nolan" },
  { "text": "Wake up with purpose, sleep with peace.", "author": "Tessa Bloom" },
  { "text": "One small act of courage can change everything.", "author": "Cole Harper" },
  { "text": "The path to greatness is paved with consistency.", "author": "Amara Skye" },
  { "text": "Your best self is built, not found.", "author": "Declan Hayes" },
  { "text": "Progress may be invisible — but it’s happening.", "author": "Leah Cruz" },
  { "text": "Winners don’t wish; they work.", "author": "Mason Grey" },
  { "text": "No one can outwork someone who refuses to quit.", "author": "Ruby Lane" },
  { "text": "You’re always one decision away from a better life.", "author": "Finn Matthews" },
  { "text": "When the why is strong, the how becomes easy.", "author": "Nora James" },
  { "text": "Hard work compounds like interest — invest daily.", "author": "Eli Brooks" },
  { "text": "Success is built on quiet mornings and loud dreams.", "author": "Aiden Cross" },
  { "text": "You don’t have to be great to start, but you must start to be great.", "author": "Grace Winters" },
  { "text": "Excuses are dreams that quit early.", "author": "Owen Miles" },
  { "text": "Be brave enough to start again differently.", "author": "Luna Cole" },
  { "text": "Don’t wish for it — work for it, daily.", "author": "Leo Harper" },
  { "text": "Growth requires discomfort — wear it proudly.", "author": "Zara Flynn" },
  { "text": "The future belongs to the persistent.", "author": "Asher Quinn" },
  { "text": "When in doubt, do it scared.", "author": "Clara Beck" },
  { "text": "Let your actions make the noise of success.", "author": "Reid Monroe" },
  { "text": "Comfort zones don’t create champions.", "author": "Elena Cross" },
  { "text": "Consistency outperforms intensity.", "author": "Troy Rivers" },
  { "text": "Big goals need small, daily wins.", "author": "Arielle Park" },
  { "text": "Doubt kills more dreams than failure ever will.", "author": "Gavin Storm" },
  { "text": "The climb is hard, but the view is worth every step.", "author": "Mila Rose" },
  { "text": "Be proud of progress others can’t see.", "author": "Noah Pierce" },
  { "text": "Discomfort means you’re leveling up.", "author": "Iris Vaughn" },
  { "text": "Impossible is an opinion, not a fact.", "author": "Ronan Beck" },
  { "text": "Turn pressure into power.", "author": "Skyler Lane" },
  { "text": "A strong mindset beats a strong obstacle.", "author": "Aiden Cross" },
  { "text": "Work until your future feels familiar.", "author": "Lily Hart" },
  { "text": "Nothing changes if nothing changes.", "author": "Zane Wyatt" },
  { "text": "Hustle quietly, let success echo.", "author": "Mira Sloan" },
  { "text": "Stay patient — big things take time.", "author": "Jonas Vale" },
  { "text": "Your growth is your greatest revenge.", "author": "Evelyn Drake" },
  { "text": "Keep going — future you is watching.", "author": "Ezra Knox" },
  { "text": "Do it with passion, or not at all.", "author": "Daisy Quinn" },
  { "text": "When motivation fades, discipline remains.", "author": "Kai Monroe" },
  { "text": "You owe it to yourself to become what you dream.", "author": "Serena Cross" },
  { "text": "Believe in the process, not just the prize.", "author": "Isa Reid" },
  { "text": "Dream big, work quietly, shine loudly.", "author": "Luca Hayes" },
  { "text": "Make today count — it’s a piece of your legacy.", "author": "Tara Bloom" },
  { "text": "The grind is temporary, but pride lasts forever.", "author": "Caleb Frost" },
  { "text": "Fall in love with becoming your best self.", "author": "Hazel Reed" },
  { "text": "Every setback is a setup for a stronger comeback.", "author": "Owen Scott" },
  { "text": "Stay hungry, stay humble, stay moving.", "author": "Nina Ford" },
  { "text": "Your pace doesn’t matter — forward is forward.", "author": "Ethan Shaw" },
  { "text": "A little progress each day adds up to big change.", "author": "Maya Cole" },
  { "text": "Be unstoppable by being consistent.", "author": "Julian West" },
  { "text": "Let your purpose fuel your persistence.", "author": "Aria Flynn" },
  { "text": "Keep showing up — that’s half the victory.", "author": "Theo Nash" },
  { "text": "Big dreams need daily action.", "author": "Clara Brooks" },
  { "text": "Growth happens in motion, not in perfection.", "author": "Finn Drake" },
  { "text": "Effort never betrays you.", "author": "Nora Vale" },
  { "text": "Make discipline your best friend.", "author": "Liam Hayes" },
  { "text": "You don’t have to see the whole path, just the next step.", "author": "Isla Reed" },
  { "text": "Be the person who keeps going.", "author": "Mason Carter" },
  { "text": "Fear fades when you act anyway.", "author": "Ruby Sloan" },
  { "text": "Dream relentlessly. Act fearlessly.", "author": "Logan Quinn" },
  { "text": "Work hard in silence; let results speak.", "author": "Ava Cruz" },
  { "text": "Your dreams demand effort, not excuses.", "author": "Ezra Flynn" },
  { "text": "Do it with heart or not at all.", "author": "Sienna Park" },
  { "text": "Small steps in the right direction beat standing still.", "author": "Owen Bryce" },
  { "text": "Be so consistent they have to believe in you.", "author": "Luna Beck" },
  { "text": "Don’t be afraid to start small — be afraid to not start.", "author": "Zara Monroe" },
  { "text": "Motivation starts you, discipline finishes you.", "author": "Eli James" },
  { "text": "If you’re tired, learn to rest — not to quit.", "author": "Chloe West" },
  { "text": "Success loves those who refuse to quit.", "author": "Jude Harper" },
  { "text": "Keep working until your idols become peers.", "author": "Amara Cole" },
  { "text": "Grind now so you can shine later.", "author": "Miles Rivers" },
  { "text": "You are capable of more than you think.", "author": "Harper Knox" },
  { "text": "The effort is always worth it.", "author": "Leo Frost" },
  { "text": "Start messy, start scared, just start.", "author": "Tessa Bloom" },
  { "text": "Be proud of every step — it all counts.", "author": "Riley Stone" },
  { "text": "Courage means trying one more time.", "author": "Aiden Rowe" },
  { "text": "Your consistency writes your legacy.", "author": "Noah Vale" }
],


 "philosophical": [
  { "text": "The universe whispers truth to those who listen without ego.", "author": "Arielle Voss" },
  { "text": "Reality bends to the beliefs we dare to hold.", "author": "Julian Reeve" },
  { "text": "Silence often has more meaning than speech.", "author": "Nora Vale" },
  { "text": "Time teaches through both pain and peace.", "author": "Leo Frost" },
  { "text": "Understanding begins where judgment ends.", "author": "Isla Quinn" },
  { "text": "You are both the painter and the canvas of your life.", "author": "Ronan Beck" },
  { "text": "Freedom starts when we stop chasing approval.", "author": "Sienna Hart" },
  { "text": "The soul speaks in feelings the mind can’t translate.", "author": "Elias Cross" },
  { "text": "Every ending hides a seed of beginning.", "author": "Lena Hayes" },
  { "text": "Sometimes losing yourself is the only way to meet who you are.", "author": "Finn Matthews" },
  { "text": "Truth is not discovered; it’s remembered.", "author": "Maya Sterling" },
  { "text": "We are stories pretending to be people.", "author": "Noah Rivers" },
  { "text": "The meaning of life is the one you give it daily.", "author": "Zara Flynn" },
  { "text": "Questions are wiser than answers that end them.", "author": "Kai Turner" },
  { "text": "We see the world not as it is, but as we are.", "author": "Aria Bloom" },
  { "text": "To know yourself is to unlearn who you were told to be.", "author": "Eli Torres" },
  { "text": "Wisdom whispers; noise argues.", "author": "Ava Monroe" },
  { "text": "Peace begins when certainty ends.", "author": "Miles Rowan" },
  { "text": "The mind builds prisons, and awareness finds the keys.", "author": "Leah Cruz" },
  { "text": "Every thought is a seed — choose what you grow.", "author": "Declan Hayes" },
  { "text": "We are infinite beings pretending to have limits.", "author": "Chloe Rivers" },
  { "text": "Time is a mirror reflecting our choices.", "author": "Logan Bryce" },
  { "text": "You are not what happens to you; you are what you make of it.", "author": "Nina Ford" },
  { "text": "Wisdom lives where the ego dies.", "author": "Owen Miles" },
  { "text": "The more you seek control, the less you find peace.", "author": "Clara Beck" },
  { "text": "We age not by years, but by our willingness to change.", "author": "Jonas Vale" },
  { "text": "Truth doesn’t shout; it waits to be noticed.", "author": "Amara Skye" },
  { "text": "Awareness is the birthplace of transformation.", "author": "Theo Reed" },
  { "text": "You are the observer, not the storm.", "author": "Hazel Reed" },
  { "text": "Life is a riddle answered through living.", "author": "Evan Frost" },
  { "text": "The moment you stop seeking meaning, you start living it.", "author": "Ruby Lane" },
  { "text": "Even chaos has a pattern for those patient enough to see it.", "author": "Luna Cole" },
  { "text": "Stillness is the sound of truth speaking.", "author": "Caleb North" },
  { "text": "We chase the future while standing on eternity.", "author": "Aiden Cross" },
  { "text": "Perception is the architect of our reality.", "author": "Mira Sloan" },
  { "text": "Simplicity is the highest form of understanding.", "author": "Kai Monroe" },
  { "text": "Nothing external can fill what’s empty within.", "author": "Serena Cross" },
  { "text": "The universe evolves through questions, not conclusions.", "author": "Ezra Knox" },
  { "text": "We are temporary expressions of something eternal.", "author": "Ivy Monroe" },
  { "text": "The mind fears change; the soul craves it.", "author": "Reid Monroe" },
  { "text": "Meaning blooms when we stop demanding it.", "author": "Ava Cruz" },
  { "text": "Pain is the universe’s way of waking us up.", "author": "Zane Wyatt" },
  { "text": "We search for truth in books written inside ourselves.", "author": "Harper Quinn" },
  { "text": "Ego seeks control; spirit seeks connection.", "author": "Sienna Vale" },
  { "text": "We spend life collecting identities, only to return to being.", "author": "Mason Grey" },
  { "text": "Wisdom is not found — it’s remembered.", "author": "Owen Scott" },
  { "text": "Reality is a mirror reflecting our inner state.", "author": "Tara Bloom" },
  { "text": "You cannot hold light and shadow apart — both make you whole.", "author": "Eli Brooks" },
  { "text": "Freedom is realizing you were never trapped.", "author": "Nora James" },
  { "text": "Truth doesn’t change; only our understanding does.", "author": "Miles Rivers" },
  { "text": "The present moment is eternity’s favorite disguise.", "author": "Isla Reed" },
  { "text": "We measure time by moments that move our hearts.", "author": "Riley Stone" },
  { "text": "Every truth sounds like rebellion at first.", "author": "Leo Harper" },
  { "text": "The self is a story we keep rewriting.", "author": "Julian West" },
  { "text": "To see clearly, stop looking for answers.", "author": "Zara Monroe" },
  { "text": "Knowledge fills the mind; wisdom empties it.", "author": "Hazel King" },
  { "text": "We are both the question and the answer.", "author": "Ezra Flynn" },
  { "text": "Awakening feels like loss before it feels like freedom.", "author": "Mila Rose" },
  { "text": "Life hides its beauty in the ordinary.", "author": "Finn Drake" },
  { "text": "Clarity arrives when noise finally leaves.", "author": "Luca Hayes" },
  { "text": "We become wise not by adding, but by letting go.", "author": "Amara Cole" },
  { "text": "Our beliefs are just the clothes truth wears.", "author": "Tessa Bloom" },
  { "text": "There’s peace in accepting not knowing.", "author": "Kai Monroe" },
  { "text": "Every perspective is a fragment of truth.", "author": "Owen Bryce" },
  { "text": "The soul doesn’t speak in words — it feels.", "author": "Luna Beck" },
  { "text": "We are all mirrors reflecting each other’s lessons.", "author": "Jonas Vale" },
  { "text": "Nothing real can be threatened; nothing unreal exists.", "author": "Maya Cole" },
  { "text": "The more you know, the less you need.", "author": "Isa Reid" },
  { "text": "We think to understand, but feel to know.", "author": "Clara Brooks" },
  { "text": "Truth cannot be taught — only realized.", "author": "Daisy Quinn" },
  { "text": "Every paradox is an invitation to grow.", "author": "Ezra Vale" },
  { "text": "We meet ourselves in the reflections of others.", "author": "Julian Beck" },
  { "text": "Existence is the art of being aware.", "author": "Riley Grant" },
  { "text": "Peace is found in surrender, not in struggle.", "author": "Liam Hayes" },
  { "text": "Life is the universe experiencing itself curiously.", "author": "Nora Vale" },
  { "text": "The wisest questions are the ones that stay unanswered.", "author": "Mason Carter" },
  { "text": "We are the dreamers dreaming reality awake.", "author": "Harper Knox" },
  { "text": "The soul never rushes; it unfolds.", "author": "Isla Quinn" },
  { "text": "Light and darkness are partners, not enemies.", "author": "Ruby Sloan" },
  { "text": "Only by losing certainty do we find truth.", "author": "Aiden Rowe" },
  { "text": "Reality listens to the thoughts we repeat.", "author": "Sienna Hart" },
  { "text": "Every truth begins as a whisper.", "author": "Caleb Frost" },
  { "text": "Meaning is not given; it’s created.", "author": "Lena Hayes" },
  { "text": "We are both the ocean and the wave.", "author": "Owen Miles" },
  { "text": "There’s beauty in what we’ll never understand.", "author": "Leah Cruz" },
  { "text": "The greatest journey is inward.", "author": "Mira Sloan" },
  { "text": "We are time travelers in the present moment.", "author": "Zane Wyatt" },
  { "text": "The wise learn from silence more than speech.", "author": "Kai Monroe" },
  { "text": "We grow through contradictions, not comfort.", "author": "Ezra Knox" },
  { "text": "Consciousness is life looking at itself.", "author": "Miles Rowan" },
  { "text": "Our perception of limits defines what’s possible.", "author": "Jonas Vale" },
  { "text": "Every thought paints reality’s canvas.", "author": "Ronan Beck" },
  { "text": "You are the sky — thoughts are just weather.", "author": "Luna Cole" },
  { "text": "Truth is patient — it waits for silence.", "author": "Tara Bloom" }
],

   "funny": [
  { "text": "Life’s too short to match socks.", "author": "Tessa Bloom" },
  { "text": "I’m not lazy — I’m on energy-saving mode.", "author": "Leo Frost" },
  { "text": "My bed and I have a strong relationship. It’s just complicated in the mornings.", "author": "Ruby Lane" },
  { "text": "Common sense is like deodorant — the people who need it never use it.", "author": "Owen Miles" },
  { "text": "I put ‘pro’ in procrastination.", "author": "Luna Beck" },
  { "text": "Coffee: because adulting is hard.", "author": "Kai Monroe" },
  { "text": "Don’t grow up — it’s a trap.", "author": "Ava Cruz" },
  { "text": "I whisper to Wi-Fi routers hoping for stronger connections.", "author": "Ezra Knox" },
  { "text": "Exercise? I thought you said ‘extra fries.’", "author": "Isla Reed" },
  { "text": "I’m multitasking: I can listen, ignore, and forget at the same time.", "author": "Finn Drake" },
  { "text": "I don’t trip — I perform random gravity checks.", "author": "Sienna Hart" },
  { "text": "My favorite exercise is a cross between a lunge and a crunch — I call it lunch.", "author": "Jonas Vale" },
  { "text": "I’m on a seafood diet. I see food, and I eat it.", "author": "Nora James" },
  { "text": "Sarcasm is my cardio.", "author": "Eli Torres" },
  { "text": "Running late counts as cardio, right?", "author": "Lena Hayes" },
  { "text": "I told my suitcase there will be no vacations this year. Now it’s full of emotional baggage.", "author": "Arielle Voss" },
  { "text": "I’m not arguing; I’m just explaining why I’m right.", "author": "Logan Bryce" },
  { "text": "If Monday had a face, I’d hit snooze on it.", "author": "Hazel Reed" },
  { "text": "I’d agree with you, but then we’d both be wrong.", "author": "Caleb North" },
  { "text": "If stress burned calories, I’d be invisible.", "author": "Zara Flynn" },
  { "text": "Some people just need a high-five. In the face. With a chair.", "author": "Miles Rowan" },
  { "text": "My wallet is like an onion — opening it makes me cry.", "author": "Mason Grey" },
  { "text": "I’m not lazy, I’m just on power-saving mode.", "author": "Luna Cole" },
  { "text": "I wish my bank account filled as fast as my inbox.", "author": "Theo Reed" },
  { "text": "I told my phone we were taking a break — now it’s seeing other people.", "author": "Ava Monroe" },
  { "text": "I’m not a morning person. Or an afternoon person. Let’s just skip to the weekend.", "author": "Nina Ford" },
  { "text": "Why fall in love when you can fall asleep?", "author": "Eli Brooks" },
  { "text": "I like my coffee black and my humor darker.", "author": "Julian Beck" },
  { "text": "I’m not bossy — I just have better ideas.", "author": "Maya Sterling" },
  { "text": "They said ‘don’t try this at home,’ so I went to my friend’s house.", "author": "Jonas Vale" },
  { "text": "I finally got 8 hours of sleep. It took me 3 days, but I did it.", "author": "Zane Wyatt" },
  { "text": "Dear math, I’m not a therapist. Solve your own problems.", "author": "Isla King" },
  { "text": "I’d like to thank coffee for getting me out of bed and sarcasm for getting me through the day.", "author": "Tara Bloom" },
  { "text": "I need a six-month vacation twice a year.", "author": "Ezra Flynn" },
  { "text": "If my brain had a loading bar, it’d be stuck at 99%.", "author": "Ronan Beck" },
  { "text": "I told my mirror to be honest, now we’re not on speaking terms.", "author": "Chloe Rivers" },
  { "text": "Out of my mind — back in five minutes.", "author": "Aiden Cross" },
  { "text": "Whoever said laughter is the best medicine clearly never had Wi-Fi issues.", "author": "Aria Bloom" },
  { "text": "My life feels like a group project where I do all the work.", "author": "Mira Sloan" },
  { "text": "I’m not weird — I’m limited edition.", "author": "Kai Turner" },
  { "text": "I thought I wanted a career — turns out I just wanted a paycheck.", "author": "Evelyn Drake" },
  { "text": "Adulting is soup, and I’m a fork.", "author": "Owen Scott" },
  { "text": "I love long romantic walks to the fridge.", "author": "Clara Beck" },
  { "text": "I’m on a 30-day diet. So far, I’ve lost 15 days.", "author": "Leah Cruz" },
  { "text": "If at first you don’t succeed, order pizza.", "author": "Finn Matthews" },
  { "text": "I followed my heart — it led me to the couch.", "author": "Luna Beck" },
  { "text": "I told my phone I needed space. It gave me 404 errors.", "author": "Noah Rivers" },
  { "text": "When nothing goes right, go left — there’s probably snacks there.", "author": "Tessa Bloom" },
  { "text": "I don’t snore. I dream I’m a motorcycle.", "author": "Miles Rivers" },
  { "text": "I’m on a whiskey diet — I’ve lost three days already.", "author": "Zara Monroe" },
  { "text": "If sarcasm burned calories, I’d be a supermodel.", "author": "Logan Quinn" },
  { "text": "I can’t adult today. Please don’t make me.", "author": "Sienna Hart" },
  { "text": "Brains are awesome. I wish everyone had one.", "author": "Mason Carter" },
  { "text": "I’m in shape — round is a shape.", "author": "Julian West" },
  { "text": "Some days I amaze myself. Other days I put my keys in the fridge.", "author": "Hazel Reed" },
  { "text": "The early bird can have the worm — I’ll take coffee instead.", "author": "Ezra Knox" },
  { "text": "I like my bed more than most people.", "author": "Nora Vale" },
  { "text": "My mood depends on how good my hair looks today.", "author": "Eli Torres" },
  { "text": "I told my alarm clock we’re breaking up.", "author": "Ruby Sloan" },
  { "text": "If I were any lazier, I’d be in reverse.", "author": "Owen Miles" },
  { "text": "I’m not short — I’m concentrated awesome.", "author": "Lena Hayes" },
  { "text": "If Monday were a person, it’d need therapy.", "author": "Ava Monroe" },
  { "text": "I’d exercise, but it makes my coffee spill.", "author": "Caleb North" },
  { "text": "My phone battery lasts longer than my motivation.", "author": "Jonas Vale" },
  { "text": "If adulting had a tutorial, I’d still skip it.", "author": "Tara Bloom" },
  { "text": "I’m not clumsy — the floor just hates me.", "author": "Leo Harper" },
  { "text": "Some call it chaos, I call it home décor.", "author": "Isla Reed" },
  { "text": "My brain has too many tabs open.", "author": "Zane Wyatt" },
  { "text": "Who needs a personal trainer when stress runs me every day?", "author": "Arielle Voss" },
  { "text": "Dear sleep: I’m sorry we broke up. I want you back.", "author": "Miles Rowan" },
  { "text": "My favorite childhood memory is not paying bills.", "author": "Kai Monroe" },
  { "text": "If you can’t convince them, confuse them.", "author": "Julian Beck" },
  { "text": "I’m not late — I’m just early for tomorrow.", "author": "Eli Brooks" },
  { "text": "Some days you eat salad; some days you eat 12 donuts. It’s called balance.", "author": "Clara Brooks" },
  { "text": "I don’t need anger management. I need people to stop being stupid.", "author": "Luna Cole" },
  { "text": "I thought I was indecisive, but now I’m not sure.", "author": "Finn Drake" },
  { "text": "Out of coffee, out of patience, out of office.", "author": "Sienna Vale" },
  { "text": "I dance like no one’s watching — because they’re not; they’re scrolling.", "author": "Zara Flynn" },
  { "text": "My password is the same as my mood: tired.", "author": "Hazel King" },
  { "text": "I don’t make mistakes; I create unexpected plot twists.", "author": "Mira Sloan" },
  { "text": "I like long walks — especially when they’re taken by people who annoy me.", "author": "Kai Turner" },
  { "text": "I told Alexa to clean my room. She laughed.", "author": "Nina Ford" },
  { "text": "I don’t need a mood ring — I have a face.", "author": "Jonas Vale" },
  { "text": "Don’t follow your dreams — hit snooze and catch them later.", "author": "Miles Rivers" },
  { "text": "If my life had a soundtrack, it’d be buffering.", "author": "Riley Stone" },
  { "text": "I’m not arguing; I’m just passionately expressing my rightness.", "author": "Ezra Vale" },
  { "text": "Of course I talk to myself. I need expert advice.", "author": "Luna Beck" },
  { "text": "Life without coffee is like a broken pencil — pointless.", "author": "Caleb Frost" },
  { "text": "I’m not messy — I’m creatively organized.", "author": "Leah Cruz" },
  { "text": "I don’t sweat — I sparkle.", "author": "Ava Cruz" },
  { "text": "I’m allergic to mornings and responsibilities.", "author": "Julian West" },
  { "text": "My hobbies include eating and complaining about getting fat.", "author": "Nora Vale" },
  { "text": "If at first you don’t succeed, blame Mercury retrograde.", "author": "Ruby Lane" },
  { "text": "I’d lose weight, but I hate losing.", "author": "Eli Torres" },
  { "text": "My body is a temple — ancient and in need of restoration.", "author": "Zane Wyatt" }
],

"mindful": [
  { "text": "Breathe deeply — peace begins within.", "author": "Isla Reed" },
  { "text": "Stillness is not the absence of life but the discovery of it.", "author": "Leo Frost" },
  { "text": "Calm minds create clear paths.", "author": "Ruby Lane" },
  { "text": "Gratitude turns ordinary days into blessings.", "author": "Luna Beck" },
  { "text": "Let go of what you can’t carry gracefully.", "author": "Ava Cruz" },
  { "text": "Presence is the purest form of peace.", "author": "Miles Rowan" },
  { "text": "Happiness grows where acceptance blooms.", "author": "Mira Sloan" },
  { "text": "The quiet mind sees the loud truth.", "author": "Ezra Knox" },
  { "text": "Be where your feet are.", "author": "Zara Flynn" },
  { "text": "In simplicity, we rediscover abundance.", "author": "Jonas Vale" },
  { "text": "Peace is not something you find; it’s something you allow.", "author": "Nina Ford" },
  { "text": "A calm heart sees clearly even in chaos.", "author": "Theo Reed" },
  { "text": "Breathe — it’s your body’s way of whispering that you’re alive.", "author": "Hazel Reed" },
  { "text": "When you pause, the world opens.", "author": "Lena Hayes" },
  { "text": "The present moment is life’s favorite hiding place.", "author": "Eli Torres" },
  { "text": "You can’t calm the storm, but you can calm yourself.", "author": "Julian Beck" },
  { "text": "Peace grows in the garden of gratitude.", "author": "Kai Monroe" },
  { "text": "The quieter you become, the more you hear.", "author": "Mason Grey" },
  { "text": "Every breath is a new beginning.", "author": "Isla King" },
  { "text": "Slow down — your soul moves slower than your schedule.", "author": "Caleb North" },
  { "text": "The moment you breathe consciously, you return home.", "author": "Aria Bloom" },
  { "text": "Peace doesn’t come from escaping life but embracing it gently.", "author": "Clara Beck" },
  { "text": "Even still water reflects the sky.", "author": "Ezra Vale" },
  { "text": "Rest is not laziness; it’s renewal.", "author": "Ava Monroe" },
  { "text": "Mindfulness is the art of noticing the miracle of now.", "author": "Finn Drake" },
  { "text": "You don’t need more time; you need more presence.", "author": "Kai Turner" },
  { "text": "The pause between breaths holds eternity.", "author": "Nora Vale" },
  { "text": "Awareness is the seed of transformation.", "author": "Owen Miles" },
  { "text": "Peace is not a place; it’s a practice.", "author": "Tara Bloom" },
  { "text": "Surrender is not giving up — it’s tuning in.", "author": "Riley Stone" },
  { "text": "Be gentle — the world is as soft as your attention.", "author": "Hazel King" },
  { "text": "Every mindful breath is an act of healing.", "author": "Julian West" },
  { "text": "Let silence be your sanctuary.", "author": "Miles Rivers" },
  { "text": "Still moments grow strong roots.", "author": "Zane Wyatt" },
  { "text": "Notice how life breathes through you, not at you.", "author": "Maya Sterling" },
  { "text": "In slowing down, we catch up to ourselves.", "author": "Sienna Hart" },
  { "text": "The mind rests when the heart feels safe.", "author": "Aiden Cross" },
  { "text": "Don’t chase calm — create it.", "author": "Leah Cruz" },
  { "text": "Peace lives in the pauses we skip.", "author": "Eli Brooks" },
  { "text": "Softness is not weakness; it’s strength at peace.", "author": "Luna Cole" },
  { "text": "The moment you notice your breath, you wake up to life.", "author": "Kai Monroe" },
  { "text": "Worry is a story; presence is truth.", "author": "Jonas Vale" },
  { "text": "Choose calm even when chaos invites you in.", "author": "Arielle Voss" },
  { "text": "In awareness, the ordinary becomes sacred.", "author": "Mason Carter" },
  { "text": "Gratitude transforms routine into ritual.", "author": "Tessa Bloom" },
  { "text": "Every moment asks for your attention as a gift.", "author": "Ezra Knox" },
  { "text": "Stillness teaches what words cannot.", "author": "Nina Ford" },
  { "text": "When the mind quiets, the heart remembers.", "author": "Julian Beck" },
  { "text": "Observe without judgment — that’s real peace.", "author": "Ruby Sloan" },
  { "text": "Don’t rush the moment trying to reach the next.", "author": "Liam Hayes" },
  { "text": "The simple act of noticing changes everything.", "author": "Noah Rivers" },
  { "text": "Peace is found in presence, not perfection.", "author": "Mira Sloan" },
  { "text": "Let your breath anchor you to now.", "author": "Clara Brooks" },
  { "text": "A quiet mind opens loud truths.", "author": "Ezra Vale" },
  { "text": "Be kind to this moment — it’s the only one you own.", "author": "Kai Turner" },
  { "text": "Serenity begins with a single mindful breath.", "author": "Finn Matthews" },
  { "text": "Your inner peace is your greatest wealth.", "author": "Isla Reed" },
  { "text": "Listen deeply — the silence has something to say.", "author": "Leo Harper" },
  { "text": "Even clouds don’t worry about their shape.", "author": "Miles Rowan" },
  { "text": "Awareness turns repetition into reflection.", "author": "Nora Vale" },
  { "text": "Happiness hides in the pauses we overlook.", "author": "Hazel Reed" },
  { "text": "Do less, feel more.", "author": "Lena Hayes" },
  { "text": "Let the moment teach you how to stay.", "author": "Jonas Vale" },
  { "text": "Gratitude turns small things into miracles.", "author": "Ava Cruz" },
  { "text": "Even the act of slowing down is progress.", "author": "Owen Scott" },
  { "text": "Peace is not far — it’s just quiet.", "author": "Zara Monroe" },
  { "text": "You can’t be present and anxious at the same time.", "author": "Eli Torres" },
  { "text": "Let the day unfold instead of being controlled.", "author": "Miles Rivers" },
  { "text": "Every breath resets the soul.", "author": "Kai Monroe" },
  { "text": "Simplicity is the highest sophistication of peace.", "author": "Mira Sloan" },
  { "text": "Breathe, smile, repeat.", "author": "Aiden Cross" },
  { "text": "Stillness is the loudest wisdom.", "author": "Caleb Frost" },
  { "text": "Presence doesn’t ask for effort — only attention.", "author": "Ezra Knox" },
  { "text": "Let calm be contagious.", "author": "Ruby Lane" },
  { "text": "Even a single mindful breath changes your world.", "author": "Nina Ford" },
  { "text": "Peace flows from acceptance, not control.", "author": "Julian West" },
  { "text": "Moments don’t need meaning to be beautiful.", "author": "Luna Beck" },
  { "text": "Rest is rebellion in a world obsessed with speed.", "author": "Hazel King" },
  { "text": "Awareness makes the simple sacred.", "author": "Miles Rowan" },
  { "text": "The soul breathes through stillness.", "author": "Clara Beck" },
  { "text": "Let silence be your conversation with the universe.", "author": "Theo Reed" },
  { "text": "Peace doesn’t arrive — it’s revealed.", "author": "Tara Bloom" },
  { "text": "You are enough, even in your stillness.", "author": "Arielle Voss" },
  { "text": "Inhale calm, exhale control.", "author": "Kai Monroe" },
  { "text": "Notice the small things — they hold big peace.", "author": "Zane Wyatt" },
  { "text": "Let go. That’s where freedom lives.", "author": "Ezra Vale" },
  { "text": "Serenity is just awareness without resistance.", "author": "Leah Cruz" },
  { "text": "Pause — even time needs to breathe.", "author": "Julian Beck" },
  { "text": "A mindful heart is never truly heavy.", "author": "Isla Reed" },
  { "text": "Be fully here; nowhere else exists.", "author": "Miles Rivers" },
  { "text": "Every breath writes a new chapter of peace.", "author": "Nora Vale" },
  { "text": "Stillness is strength disguised as softness.", "author": "Maya Sterling" },
  { "text": "Listen — even your heartbeat has wisdom.", "author": "Finn Drake" },
  { "text": "Peace is what remains when the noise leaves.", "author": "Ruby Sloan" },
  { "text": "Breathe slowly. The moment is waiting for you.", "author": "Luna Cole" },
  { "text": "Gratitude is mindfulness in action.", "author": "Aiden Rowe" },
  { "text": "In the present, everything is already enough.", "author": "Kai Monroe" },
  { "text": "Peace lives in the spaces between thoughts.", "author": "Ezra Knox" }
],


    "love": [
  { "text": "True love speaks softly but stays loudly.", "author": "Ava Monroe" },
  { "text": "Connection thrives where honesty lives.", "author": "Julian Beck" },
  { "text": "The right person feels like peace, not fireworks.", "author": "Mira Sloan" },
  { "text": "Love doesn’t complete you; it celebrates you.", "author": "Eli Torres" },
  { "text": "To be understood is a kind of magic.", "author": "Luna Beck" },
  { "text": "Hearts heal best with gentle hands.", "author": "Miles Rowan" },
  { "text": "Distance means little when souls are close.", "author": "Kai Monroe" },
  { "text": "Kindness is the most fluent language of love.", "author": "Ruby Sloan" },
  { "text": "Love’s real beauty is in its imperfection.", "author": "Finn Drake" },
  { "text": "Sometimes goodbye is the kindest form of love.", "author": "Nina Ford" },
  { "text": "Real love doesn’t demand; it understands.", "author": "Theo Reed" },
  { "text": "Love is not found; it’s built, word by word.", "author": "Hazel Reed" },
  { "text": "You can’t lose what was given freely.", "author": "Mason Carter" },
  { "text": "The best love feels like home, not escape.", "author": "Isla Reed" },
  { "text": "Hearts speak a language words can’t translate.", "author": "Ezra Knox" },
  { "text": "Love grows best where gratitude is planted.", "author": "Julian West" },
  { "text": "When love is real, silence feels full.", "author": "Miles Rivers" },
  { "text": "True affection doesn’t cage — it frees.", "author": "Lena Hayes" },
  { "text": "To love deeply is to see divinity in another.", "author": "Zane Wyatt" },
  { "text": "Love is not perfect, but it is always honest.", "author": "Clara Beck" },
  { "text": "Real love isn’t about possession — it’s about presence.", "author": "Kai Turner" },
  { "text": "Love is strongest when it listens, not speaks.", "author": "Tara Bloom" },
  { "text": "Every ‘I love you’ should come with patience.", "author": "Jonas Vale" },
  { "text": "The right love doesn’t rush — it unfolds.", "author": "Ava Cruz" },
  { "text": "Love is the courage to stay soft in a hard world.", "author": "Ezra Vale" },
  { "text": "A heart that forgives is a heart that truly loves.", "author": "Nora Vale" },
  { "text": "Love grows in the soil of understanding.", "author": "Miles Rowan" },
  { "text": "You know it’s love when their happiness feels like yours.", "author": "Riley Stone" },
  { "text": "True love doesn’t rescue; it reminds you of your wings.", "author": "Isla King" },
  { "text": "To love is to see someone’s chaos and stay anyway.", "author": "Maya Sterling" },
  { "text": "Love is not something to find, but to become.", "author": "Arielle Voss" },
  { "text": "Kindness is love’s truest expression.", "author": "Leo Frost" },
  { "text": "Love matures when ego dissolves.", "author": "Hazel King" },
  { "text": "Every glance writes a small love poem.", "author": "Julian Beck" },
  { "text": "Love whispers louder than desire.", "author": "Mira Sloan" },
  { "text": "Even distance bends for hearts aligned.", "author": "Kai Monroe" },
  { "text": "Love isn’t possession — it’s partnership.", "author": "Nina Ford" },
  { "text": "The purest love expects nothing but presence.", "author": "Ezra Knox" },
  { "text": "Love is when two hearts exhale in the same rhythm.", "author": "Finn Matthews" },
  { "text": "You can’t fake warmth — love knows the difference.", "author": "Lena Hayes" },
  { "text": "Real love accepts your darkness and helps you find light.", "author": "Miles Rivers" },
  { "text": "Love asks you to show up, not to be perfect.", "author": "Ruby Lane" },
  { "text": "When love is kind, everything else aligns.", "author": "Aiden Cross" },
  { "text": "Love is an echo that never fades.", "author": "Caleb North" },
  { "text": "The bravest act is to love again after heartbreak.", "author": "Mason Grey" },
  { "text": "Sometimes love is staying; sometimes it’s letting go.", "author": "Tessa Bloom" },
  { "text": "Every love story teaches us a truth about ourselves.", "author": "Ezra Vale" },
  { "text": "Love grows through patience, not perfection.", "author": "Kai Turner" },
  { "text": "The gentlest hearts love the deepest.", "author": "Isla Reed" },
  { "text": "True love never competes — it completes.", "author": "Julian West" },
  { "text": "Love’s real test is how it behaves when it’s hard.", "author": "Hazel Reed" },
  { "text": "Sometimes love means choosing peace over being right.", "author": "Leo Harper" },
  { "text": "Love thrives in honesty, not in harmony alone.", "author": "Miles Rowan" },
  { "text": "Love’s language is attention.", "author": "Clara Beck" },
  { "text": "A gentle touch can heal what words cannot.", "author": "Ezra Knox" },
  { "text": "Love doesn’t promise forever — it offers presence now.", "author": "Nora Vale" },
  { "text": "To love is to see beauty where others see flaws.", "author": "Finn Drake" },
  { "text": "Real love grows through imperfections.", "author": "Mira Sloan" },
  { "text": "Love asks for vulnerability, not performance.", "author": "Kai Monroe" },
  { "text": "Every act of love is an act of faith.", "author": "Ruby Sloan" },
  { "text": "Love’s beauty lies in its truth, not its comfort.", "author": "Jonas Vale" },
  { "text": "The best kind of love is quiet but certain.", "author": "Ava Monroe" },
  { "text": "To love deeply is to risk completely — and it’s worth it.", "author": "Miles Rivers" },
  { "text": "Love grows in the spaces between words.", "author": "Luna Beck" },
  { "text": "You can’t love someone you want to change.", "author": "Julian Beck" },
  { "text": "Every real connection begins with kindness.", "author": "Hazel King" },
  { "text": "The heart knows before the mind can explain.", "author": "Theo Reed" },
  { "text": "Love feels like recognition, not discovery.", "author": "Mira Sloan" },
  { "text": "Even in silence, love can speak volumes.", "author": "Eli Torres" },
  { "text": "Love is the courage to stay open.", "author": "Lena Hayes" },
  { "text": "Love grows best in honest soil.", "author": "Kai Turner" },
  { "text": "The softest hearts have survived the hardest storms.", "author": "Miles Rowan" },
  { "text": "Love is not about fixing — it’s about accepting.", "author": "Ava Cruz" },
  { "text": "When two souls meet in truth, they never part.", "author": "Ezra Vale" },
  { "text": "Love isn’t loud; it’s consistent.", "author": "Finn Matthews" },
  { "text": "Real love brings peace, not confusion.", "author": "Clara Beck" },
  { "text": "Every act of care is a love letter.", "author": "Maya Sterling" },
  { "text": "To love is to listen without defense.", "author": "Zane Wyatt" },
  { "text": "Love is felt, not proven.", "author": "Ruby Lane" },
  { "text": "The truest love sees the soul, not the surface.", "author": "Jonas Vale" },
  { "text": "You don’t find love by searching — you find it by being ready.", "author": "Julian Beck" },
  { "text": "Love remains even when presence fades.", "author": "Kai Monroe" },
  { "text": "Love is the art of being gentle with another’s story.", "author": "Miles Rowan" },
  { "text": "Love thrives where patience lives.", "author": "Isla Reed" },
  { "text": "Kindness is the heartbeat of lasting love.", "author": "Ezra Knox" },
  { "text": "To be loved is to be seen completely and accepted anyway.", "author": "Hazel Reed" },
  { "text": "Love doesn’t fix pain — it holds it tenderly.", "author": "Nina Ford" },
  { "text": "Love is a choice we make again and again.", "author": "Ava Monroe" },
  { "text": "Even when it ends, love teaches us how to begin again.", "author": "Luna Cole" },
  { "text": "The most beautiful love is the one that feels safe.", "author": "Mira Sloan" },
  { "text": "Love is not a feeling — it’s a daily devotion.", "author": "Julian West" },
  { "text": "Every ‘I love you’ should be lived, not just said.", "author": "Miles Rivers" },
  { "text": "Love endures where pride surrenders.", "author": "Ezra Vale" },
  { "text": "To love someone is to grow beside them, not around them.", "author": "Kai Turner" },
  { "text": "Love’s light glows brightest through kindness.", "author": "Ruby Sloan" },
  { "text": "Love is the quiet miracle that changes everything.", "author": "Aiden Cross" },
  { "text": "The heart recognizes home long before the mind does.", "author": "Theo Reed" }
],

  "growth": [
  { "text": "Don’t shrink to fit rooms you’ve outgrown.", "author": "Ava Cruz" },
  { "text": "You owe yourself the love you give so freely.", "author": "Ezra Vale" },
  { "text": "Confidence is quiet — insecurity is loud.", "author": "Kai Turner" },
  { "text": "Fear fades when purpose speaks louder.", "author": "Miles Rowan" },
  { "text": "Glow from within and watch the world reflect it.", "author": "Ruby Lane" },
  { "text": "Be bold enough to be disliked for your authenticity.", "author": "Julian Beck" },
  { "text": "Courage doesn’t roar; it whispers ‘try again.’", "author": "Lena Hayes" },
  { "text": "You can’t bloom in soil that doubts your roots.", "author": "Mira Sloan" },
  { "text": "Growth begins where comfort ends.", "author": "Finn Drake" },
  { "text": "Keep evolving — even your best self can be better.", "author": "Nina Ford" },
  { "text": "Failure is not the end — it’s the teacher.", "author": "Theo Reed" },
  { "text": "Every setback is just a seed for comeback.", "author": "Hazel Reed" },
  { "text": "Outgrow your fears before they outgrow you.", "author": "Isla Reed" },
  { "text": "The journey inward always leads forward.", "author": "Miles Rivers" },
  { "text": "Change is uncomfortable because it’s working.", "author": "Kai Monroe" },
  { "text": "Your pace is your power — growth isn’t a race.", "author": "Mason Grey" },
  { "text": "Progress hides in persistence.", "author": "Julian West" },
  { "text": "You’re allowed to be both a masterpiece and a work in progress.", "author": "Ava Monroe" },
  { "text": "Outgrowing people doesn’t mean you stopped caring.", "author": "Ezra Knox" },
  { "text": "Strength is built through gentle self-honesty.", "author": "Clara Beck" },
  { "text": "Courage is built one choice at a time.", "author": "Zane Wyatt" },
  { "text": "You won’t find growth where you feel safest.", "author": "Luna Beck" },
  { "text": "The caterpillar doesn’t fear the cocoon.", "author": "Theo Reed" },
  { "text": "Growth is just change in a kind disguise.", "author": "Ruby Sloan" },
  { "text": "Healing is just growth you can feel.", "author": "Mira Sloan" },
  { "text": "Not all progress is visible — some happens in silence.", "author": "Julian Beck" },
  { "text": "You can’t evolve by staying who you were.", "author": "Miles Rowan" },
  { "text": "Let your growth be louder than your doubt.", "author": "Nora Vale" },
  { "text": "Mistakes are just growing pains of wisdom.", "author": "Finn Matthews" },
  { "text": "Change is the price of becoming yourself.", "author": "Hazel King" },
  { "text": "Be patient — growth happens in unseen roots.", "author": "Kai Turner" },
  { "text": "Your evolution will confuse those who never grew.", "author": "Aiden Cross" },
  { "text": "Every lesson learned is self-love in disguise.", "author": "Ezra Vale" },
  { "text": "Don’t rush the process — trust your unfolding.", "author": "Lena Hayes" },
  { "text": "You can’t grow if you won’t let go.", "author": "Miles Rivers" },
  { "text": "Progress is made one brave breath at a time.", "author": "Julian Beck" },
  { "text": "Grow through what you go through.", "author": "Kai Monroe" },
  { "text": "Your growth may be invisible, but it’s happening.", "author": "Mira Sloan" },
  { "text": "Change feels like loss until it feels like freedom.", "author": "Ruby Lane" },
  { "text": "Keep watering your dreams, even when it rains doubt.", "author": "Ava Cruz" },
  { "text": "You can’t heal by hating who you were.", "author": "Finn Drake" },
  { "text": "Growth is love in motion.", "author": "Ezra Knox" },
  { "text": "Your potential is waiting behind your fear.", "author": "Miles Rowan" },
  { "text": "Transformation begins with permission.", "author": "Hazel Reed" },
  { "text": "Let your next level be built on self-kindness.", "author": "Jonas Vale" },
  { "text": "Don’t fear falling — that’s how you learn to rise.", "author": "Maya Sterling" },
  { "text": "Growth means forgiving your younger self.", "author": "Theo Reed" },
  { "text": "You’re allowed to outgrow the version of you that settled.", "author": "Nina Ford" },
  { "text": "Every challenge is an invitation to evolve.", "author": "Caleb Frost" },
  { "text": "Let curiosity replace fear.", "author": "Miles Rivers" },
  { "text": "Becoming isn’t about changing — it’s about revealing.", "author": "Ruby Sloan" },
  { "text": "The storm you survive becomes your strength.", "author": "Kai Turner" },
  { "text": "Growth is quiet — it doesn’t need to prove itself.", "author": "Ezra Vale" },
  { "text": "Each new chapter requires you to release the old one.", "author": "Julian Beck" },
  { "text": "When nothing is certain, everything can grow.", "author": "Ava Monroe" },
  { "text": "Healing and growth are sisters of the same storm.", "author": "Mira Sloan" },
  { "text": "The version of you that failed is the same one that will rise.", "author": "Hazel Reed" },
  { "text": "Keep walking — even slow progress is still forward.", "author": "Finn Matthews" },
  { "text": "You don’t bloom by force — only by patience.", "author": "Miles Rowan" },
  { "text": "Sometimes growth looks like stillness.", "author": "Luna Cole" },
  { "text": "Growth doesn’t demand speed, only consistency.", "author": "Theo Reed" },
  { "text": "The person you’re becoming will thank you for today.", "author": "Ruby Lane" },
  { "text": "Don’t dim your growth to comfort someone’s stillness.", "author": "Ezra Knox" },
  { "text": "Becoming more yourself is the ultimate success.", "author": "Kai Monroe" },
  { "text": "Pain is growth’s favorite disguise.", "author": "Julian West" },
  { "text": "Trust the process — it knows where it’s leading.", "author": "Miles Rivers" },
  { "text": "Grow toward the light, even when you can’t see it.", "author": "Ava Cruz" },
  { "text": "Every small win deserves celebration.", "author": "Mason Carter" },
  { "text": "Let progress replace perfection.", "author": "Hazel King" },
  { "text": "Your roots will hold if you keep watering them.", "author": "Finn Drake" },
  { "text": "Growth means becoming comfortable with uncertainty.", "author": "Lena Hayes" },
  { "text": "The next version of you requires new courage.", "author": "Ezra Vale" },
  { "text": "You’re not starting over — you’re starting wiser.", "author": "Miles Rowan" },
  { "text": "Let your transformation be your testimony.", "author": "Ruby Sloan" },
  { "text": "Growth isn’t loud — it’s consistent.", "author": "Kai Turner" },
  { "text": "Keep moving — discomfort is direction.", "author": "Julian Beck" },
  { "text": "Growth asks for patience, not proof.", "author": "Theo Reed" },
  { "text": "Don’t rush what’s meant to unfold slowly.", "author": "Mira Sloan" },
  { "text": "Your strength is the story of your persistence.", "author": "Miles Rivers" },
  { "text": "Every mistake is a lesson in disguise.", "author": "Finn Matthews" },
  { "text": "Be gentle — growth is still growing.", "author": "Nina Ford" },
  { "text": "Healing is growth you can feel in motion.", "author": "Luna Beck" },
  { "text": "Even small steps count in the dance of progress.", "author": "Ezra Knox" },
  { "text": "Growth is messy — that’s how it’s real.", "author": "Miles Rowan" },
  { "text": "Your evolution doesn’t need to be understood.", "author": "Kai Monroe" },
  { "text": "Keep learning, unlearning, and becoming.", "author": "Ruby Sloan" },
  { "text": "Growth isn’t linear — it’s layered.", "author": "Julian Beck" },
  { "text": "Trust the timing of your transformation.", "author": "Hazel Reed" },
  { "text": "Progress is peace in motion.", "author": "Theo Reed" },
  { "text": "You are your best project.", "author": "Ava Cruz" },
  { "text": "To grow is to say yes to the unknown.", "author": "Miles Rivers" },
  { "text": "Your challenges are sculpting your character.", "author": "Mira Sloan" },
  { "text": "Growth blooms from discomfort’s soil.", "author": "Julian West" },
  { "text": "Even the smallest step shifts the future.", "author": "Ezra Vale" },
  { "text": "Keep unfolding — you’re not done yet.", "author": "Ruby Lane" },
  { "text": "Growth is a conversation between courage and change.", "author": "Finn Drake" },
  { "text": "Every ending is the start of new growth.", "author": "Miles Rowan" }
],
"wisdom": [
  { "text": "Life is a collection of 'almosts' that teach us what truly matters.", "author": "Eleanor Vale" },
  { "text": "Every scar tells a story of survival.", "author": "Miles Rowan" },
  { "text": "Change is the only constant worth trusting.", "author": "Ava Cruz" },
  { "text": "The longest journey is from your head to your heart.", "author": "Theo Reed" },
  { "text": "Patience is the art of trusting timing.", "author": "Ruby Lane" },
  { "text": "The past is a teacher, not a destination.", "author": "Finn Drake" },
  { "text": "You can’t rewrite yesterday, but you can edit tomorrow.", "author": "Kai Monroe" },
  { "text": "Don’t count the moments — make the moments count.", "author": "Nina Ford" },
  { "text": "Life humbles those who rush and rewards those who listen.", "author": "Lena Hayes" },
  { "text": "Wisdom begins where certainty ends.", "author": "Julian Beck" },
  { "text": "Knowing yourself is the beginning of all wisdom.", "author": "Ezra Knox" },
  { "text": "The quieter you become, the more you hear.", "author": "Mira Sloan" },
  { "text": "Not all who wander are lost — some are discovering.", "author": "Miles Rivers" },
  { "text": "Experience is a cruel teacher but an effective one.", "author": "Hazel Reed" },
  { "text": "The simplest truths are often the hardest to follow.", "author": "Finn Matthews" },
  { "text": "What you resist, persists; what you embrace, transforms.", "author": "Kai Turner" },
  { "text": "Time doesn’t heal; understanding does.", "author": "Ruby Sloan" },
  { "text": "Wisdom is knowing the right question to ask.", "author": "Ava Monroe" },
  { "text": "Even silence can teach what words cannot.", "author": "Theo Reed" },
  { "text": "Sometimes the hardest lesson is learning to let go.", "author": "Nina Ford" },
  { "text": "Reflection is the mirror of progress.", "author": "Miles Rowan" },
  { "text": "The weight of knowledge is balanced by the lightness of humility.", "author": "Julian Beck" },
  { "text": "Seek understanding, not victory.", "author": "Ezra Vale" },
  { "text": "A wise heart listens twice as much as it speaks.", "author": "Mira Sloan" },
  { "text": "Every end contains the seed of a beginning.", "author": "Lena Hayes" },
  { "text": "Patience is silent strength.", "author": "Hazel Reed" },
  { "text": "To know the world, start with knowing yourself.", "author": "Finn Drake" },
  { "text": "Life’s answers come to those who wait with curiosity.", "author": "Kai Monroe" },
  { "text": "Clarity is born from stillness, not noise.", "author": "Ruby Lane" },
  { "text": "Wisdom often comes disguised as suffering.", "author": "Miles Rivers" },
  { "text": "A thoughtful mind is a peaceful mind.", "author": "Nina Ford" },
  { "text": "Mistakes are chapters, not conclusions.", "author": "Theo Reed" },
  { "text": "Knowledge is learned; wisdom is lived.", "author": "Ava Cruz" },
  { "text": "The deeper the experience, the richer the lesson.", "author": "Julian West" },
  { "text": "Change your perspective, change your life.", "author": "Ezra Knox" },
  { "text": "Life speaks softly; you must listen carefully.", "author": "Mira Sloan" },
  { "text": "Understanding grows where judgment fades.", "author": "Lena Hayes" },
  { "text": "The road to wisdom is paved with mistakes.", "author": "Finn Matthews" },
  { "text": "Sometimes wisdom is knowing when to speak and when to remain silent.", "author": "Miles Rowan" },
  { "text": "Life’s lessons arrive dressed in ordinary moments.", "author": "Hazel Reed" },
  { "text": "The more you learn, the more you realize how little you know.", "author": "Kai Turner" },
  { "text": "Experience teaches, but reflection reveals.", "author": "Ruby Sloan" },
  { "text": "Clarity is found in the space between thoughts.", "author": "Nina Ford" },
  { "text": "Life rewards those who observe before acting.", "author": "Theo Reed" },
  { "text": "Wisdom is seeing beyond what the eyes can touch.", "author": "Ava Monroe" },
  { "text": "True understanding comes without haste.", "author": "Miles Rivers" },
  { "text": "The wisest action is often the one least spoken of.", "author": "Julian Beck" },
  { "text": "Time is the canvas; experience is the brush.", "author": "Ezra Vale" },
  { "text": "Even the tallest tree started as a seed in patience.", "author": "Mira Sloan" },
  { "text": "Life teaches by giving and taking equally.", "author": "Lena Hayes" },
  { "text": "The most valuable lessons are those learned quietly.", "author": "Finn Matthews" },
  { "text": "Growth without reflection is just motion.", "author": "Miles Rowan" },
  { "text": "The journey within is longer than the journey outside.", "author": "Hazel Reed" },
  { "text": "Wisdom is not knowing all answers but asking the right questions.", "author": "Kai Turner" },
  { "text": "Even in darkness, the mind can shine light.", "author": "Ruby Lane" },
  { "text": "Every failure carries the blueprint of future success.", "author": "Nina Ford" },
  { "text": "Patience turns moments into milestones.", "author": "Theo Reed" },
  { "text": "Life’s depth is measured by the quality of reflection.", "author": "Ava Cruz" },
  { "text": "A calm mind is the soil of wisdom.", "author": "Julian West" },
  { "text": "Truth is often revealed in the pauses between words.", "author": "Ezra Knox" },
  { "text": "The past is a lens, not a chain.", "author": "Mira Sloan" },
  { "text": "Knowledge is learned; wisdom is earned.", "author": "Lena Hayes" },
  { "text": "Every experience contains a lesson waiting to be uncovered.", "author": "Finn Matthews" },
  { "text": "The heart often knows what the mind cannot yet understand.", "author": "Miles Rowan" },
  { "text": "Wisdom grows when curiosity meets patience.", "author": "Hazel Reed" },
  { "text": "Reflection is the key to unlocking understanding.", "author": "Kai Monroe" },
  { "text": "Even silence can guide the soul.", "author": "Ruby Sloan" },
  { "text": "Clarity emerges when you step back from the noise.", "author": "Nina Ford" },
  { "text": "The true lesson is hidden in plain sight.", "author": "Theo Reed" },
  { "text": "Growth and wisdom are siblings of experience.", "author": "Ava Monroe" },
  { "text": "Patience allows life to reveal its secrets.", "author": "Miles Rivers" },
  { "text": "True wisdom doesn’t boast — it observes.", "author": "Julian Beck" },
  { "text": "Even the hardest truths can bring the gentlest clarity.", "author": "Ezra Vale" },
  { "text": "Time sharpens the mind and softens the heart.", "author": "Mira Sloan" },
  { "text": "Every question holds the seed of an answer.", "author": "Lena Hayes" },
  { "text": "The wisest choices are often the simplest.", "author": "Finn Matthews" },
  { "text": "Life whispers lessons to those who listen.", "author": "Miles Rowan" },
  { "text": "Experience speaks; the inexperienced only repeat.", "author": "Hazel Reed" },
  { "text": "Wisdom is patience refined by reflection.", "author": "Kai Turner" },
  { "text": "Observation is the doorway to insight.", "author": "Ruby Lane" },
  { "text": "Even fleeting moments contain timeless lessons.", "author": "Nina Ford" },
  { "text": "Understanding grows where judgment fades.", "author": "Theo Reed" },
  { "text": "The wisest journeys begin inward.", "author": "Ava Cruz" },
  { "text": "Time is a teacher that spares no one.", "author": "Julian West" },
  { "text": "Every life is a library of lessons.", "author": "Ezra Knox" },
  { "text": "Knowledge informs; wisdom transforms.", "author": "Mira Sloan" },
  { "text": "The mind can wander, but the heart must understand.", "author": "Lena Hayes" },
  { "text": "Even the longest path begins with reflection.", "author": "Finn Matthews" },
  { "text": "The subtleties of life are often the greatest teachers.", "author": "Miles Rowan" },
  { "text": "Wisdom is learning to see beyond the surface.", "author": "Hazel Reed" },
  { "text": "The best insights come from quiet observation.", "author": "Kai Turner" },
  { "text": "Growth and wisdom walk hand in hand.", "author": "Ruby Sloan" },
  { "text": "Every challenge is a classroom of its own.", "author": "Nina Ford" },
  { "text": "Life’s simplicity hides profound truths.", "author": "Theo Reed" },
  { "text": "Patience listens where haste cannot.", "author": "Ava Monroe" },
  { "text": "Even mistakes contain seeds of enlightenment.", "author": "Miles Rivers" },
  { "text": "Wisdom shines brightest in quiet reflection.", "author": "Julian Beck" },
  { "text": "Observation is the silent teacher of life.", "author": "Ezra Vale" },
  { "text": "The present is the canvas for the wise.", "author": "Mira Sloan" },
  { "text": "Learning without reflection is wasted effort.", "author": "Lena Hayes" },
  { "text": "Every insight is born from curiosity.", "author": "Finn Matthews" },
  { "text": "The heart knows what the mind has yet to grasp.", "author": "Miles Rowan" },
  { "text": "True wisdom walks softly, listens deeply, and acts kindly.", "author": "Hazel Reed" },
  { "text": "Even fleeting experiences can hold eternal lessons.", "author": "Kai Turner" },
  { "text": "Knowledge is transient; wisdom is enduring.", "author": "Ruby Lane" },
  { "text": "Life’s quiet moments often speak the loudest.", "author": "Nina Ford" },
  { "text": "Patience and observation are the architects of insight.", "author": "Theo Reed" }
],

   "positivity": [
  { "text": "Smile — it’s free sunlight for the soul.", "author": "Ella Bright" },
  { "text": "Laughter is therapy without the bill.", "author": "Maxwell Joy" },
  { "text": "Joy hides in small, overlooked corners.", "author": "Clara Hope" },
  { "text": "A happy heart is a magnet for miracles.", "author": "Leo Hart" },
  { "text": "Positivity is contagious — spread it recklessly.", "author": "Maya Shine" },
  { "text": "Every moment can be made beautiful with gratitude.", "author": "Evan Bliss" },
  { "text": "Happiness doesn’t need a reason; it just needs permission.", "author": "Sophie Light" },
  { "text": "When in doubt, dance it out.", "author": "Finn Merry" },
  { "text": "Bright minds see light even in the storm.", "author": "Nina Glow" },
  { "text": "The best day to be happy is always today.", "author": "Miles Cheer" },
  { "text": "Optimism is the fuel of possibility.", "author": "Lara Sun" },
  { "text": "Kindness is the spark that lights endless joy.", "author": "Theo Bright" },
  { "text": "Happiness blooms where hearts are free.", "author": "Ruby Gleam" },
  { "text": "Even a small smile can change someone’s day.", "author": "Ezra Glow" },
  { "text": "Gratitude turns ordinary days into blessings.", "author": "Clara Hope" },
  { "text": "Joy is a choice — choose it fiercely.", "author": "Leo Hart" },
  { "text": "Positivity grows when shared, never hoarded.", "author": "Maya Shine" },
  { "text": "Happiness is homemade.", "author": "Evan Bliss" },
  { "text": "Find beauty in the little things.", "author": "Sophie Light" },
  { "text": "Even clouds have silver linings.", "author": "Finn Merry" },
  { "text": "Let your smile be your superpower.", "author": "Nina Glow" },
  { "text": "A cheerful heart makes life lighter.", "author": "Miles Cheer" },
  { "text": "Sunshine is not outside, it’s inside.", "author": "Lara Sun" },
  { "text": "Happiness is catching, spread it everywhere.", "author": "Theo Bright" },
  { "text": "Joy grows when you nurture it daily.", "author": "Ruby Gleam" },
  { "text": "Celebrate even the smallest victories.", "author": "Ezra Glow" },
  { "text": "Optimism turns obstacles into opportunities.", "author": "Clara Hope" },
  { "text": "Happiness is a habit, not an accident.", "author": "Leo Hart" },
  { "text": "Positive thoughts create positive outcomes.", "author": "Maya Shine" },
  { "text": "A grateful heart is a magnet for joy.", "author": "Evan Bliss" },
  { "text": "The world looks brighter through kind eyes.", "author": "Sophie Light" },
  { "text": "Every day is a new chance to smile.", "author": "Finn Merry" },
  { "text": "Happiness is homemade, love is the ingredient.", "author": "Nina Glow" },
  { "text": "Your energy introduces you before you speak.", "author": "Miles Cheer" },
  { "text": "Positive minds attract positive lives.", "author": "Lara Sun" },
  { "text": "A little kindness goes a long way.", "author": "Theo Bright" },
  { "text": "Joy is not found, it’s created.", "author": "Ruby Gleam" },
  { "text": "Happiness is found in the present, not tomorrow.", "author": "Ezra Glow" },
  { "text": "Optimism is a choice worth repeating daily.", "author": "Clara Hope" },
  { "text": "Light up the world with your smile.", "author": "Leo Hart" },
  { "text": "Happiness grows when you water it with gratitude.", "author": "Maya Shine" },
  { "text": "A cheerful soul changes the atmosphere.", "author": "Evan Bliss" },
  { "text": "Positive words are seeds for brighter days.", "author": "Sophie Light" },
  { "text": "Life is brighter when you shine for others.", "author": "Finn Merry" },
  { "text": "Happiness is intentional, not accidental.", "author": "Nina Glow" },
  { "text": "Your joy is your gift to the world.", "author": "Miles Cheer" },
  { "text": "Optimism paints the world in vibrant colors.", "author": "Lara Sun" },
  { "text": "Gratitude transforms what we have into enough.", "author": "Theo Bright" },
  { "text": "Happiness is the art of finding joy in ordinary moments.", "author": "Ruby Gleam" },
  { "text": "Positivity is a ripple that spreads far and wide.", "author": "Ezra Glow" },
  { "text": "A happy heart is a resilient heart.", "author": "Clara Hope" },
  { "text": "Smile often, it costs nothing but means everything.", "author": "Leo Hart" },
  { "text": "Joy is amplified when shared.", "author": "Maya Shine" },
  { "text": "Happiness thrives in simple moments.", "author": "Evan Bliss" },
  { "text": "Your attitude colors your world.", "author": "Sophie Light" },
  { "text": "Optimism is the bridge between today and hope.", "author": "Finn Merry" },
  { "text": "Kindness is the heartbeat of happiness.", "author": "Nina Glow" },
  { "text": "Gratitude makes the soul blossom.", "author": "Miles Cheer" },
  { "text": "Happiness is contagious — spread it daily.", "author": "Lara Sun" },
  { "text": "Joy is the echo of a thankful heart.", "author": "Theo Bright" },
  { "text": "A smile can be the start of something beautiful.", "author": "Ruby Gleam" },
  { "text": "Happiness is a choice, not a circumstance.", "author": "Ezra Glow" },
  { "text": "Let positivity guide your steps.", "author": "Clara Hope" },
  { "text": "Life shines brighter when your heart glows.", "author": "Leo Hart" },
  { "text": "Choose joy even on cloudy days.", "author": "Maya Shine" },
  { "text": "A kind word is sunshine in the soul.", "author": "Evan Bliss" },
  { "text": "Happiness grows when shared, not hoarded.", "author": "Sophie Light" },
  { "text": "Every day holds a moment worth smiling for.", "author": "Finn Merry" },
  { "text": "Gratitude transforms ordinary into extraordinary.", "author": "Nina Glow" },
  { "text": "Joy is a ripple that starts within.", "author": "Miles Cheer" },
  { "text": "Optimism is a superpower everyone can wield.", "author": "Lara Sun" },
  { "text": "A positive heart creates a positive life.", "author": "Theo Bright" },
  { "text": "Happiness is nurtured, not stumbled upon.", "author": "Ruby Gleam" },
  { "text": "Smile, the world needs your light.", "author": "Ezra Glow" },
  { "text": "Positivity is the fuel for resilience.", "author": "Clara Hope" },
  { "text": "Joyful hearts see more opportunities.", "author": "Leo Hart" },
  { "text": "Happiness begins with self-kindness.", "author": "Maya Shine" },
  { "text": "Your laughter is an invitation to others to smile.", "author": "Evan Bliss" },
  { "text": "Optimism turns challenges into adventures.", "author": "Sophie Light" },
  { "text": "Every smile is a victory over negativity.", "author": "Finn Merry" },
  { "text": "Happiness is intentional, courageous, and contagious.", "author": "Nina Glow" },
  { "text": "Joy is a seed — plant it everywhere.", "author": "Miles Cheer" },
  { "text": "Positivity shines brightest in the darkest times.", "author": "Lara Sun" },
  { "text": "A grateful heart turns ordinary into extraordinary.", "author": "Theo Bright" },
  { "text": "Happiness is a practice, not a destination.", "author": "Ruby Gleam" },
  { "text": "Smile often; the world will smile back.", "author": "Ezra Glow" },
  { "text": "Joy grows when shared with others.", "author": "Clara Hope" },
  { "text": "Happiness is found in appreciating what is.", "author": "Leo Hart" },
  { "text": "Your positivity can light someone’s entire day.", "author": "Maya Shine" },
  { "text": "Optimism creates possibilities where none seem to exist.", "author": "Evan Bliss" },
  { "text": "Happiness is a reflection of a grateful heart.", "author": "Sophie Light" },
  { "text": "Let your heart be the compass of joy.", "author": "Finn Merry" },
  { "text": "A cheerful mind sees opportunities everywhere.", "author": "Nina Glow" },
  { "text": "Joy is the echo of kindness.", "author": "Miles Cheer" },
  { "text": "Happiness multiplies when shared.", "author": "Lara Sun" },
  { "text": "Smile today — it’s your superpower.", "author": "Theo Bright" },
  { "text": "Optimism is the gateway to resilience.", "author": "Ruby Gleam" },
  { "text": "Happiness is a state of mind, cultivated daily.", "author": "Ezra Glow" },
  { "text": "Joy is discovered in the simplest moments.", "author": "Clara Hope" },
  { "text": "A positive heart attracts positive experiences.", "author": "Leo Hart" },
  { "text": "Every day is brighter with gratitude.", "author": "Maya Shine" },
  { "text": "Happiness is a journey, not a destination.", "author": "Evan Bliss" }
],

"creativity": [
  { "text": "The world belongs to those who keep dreaming.", "author": "Aria Muse" },
  { "text": "Imagination is the first draft of reality.", "author": "Liam Fable" },
  { "text": "Create like no one’s judging and everyone’s inspired.", "author": "Nova Sketch" },
  { "text": "Inspiration often hides in chaos.", "author": "Eli Canvas" },
  { "text": "Every blank page holds infinite worlds.", "author": "Zara Dream" },
  { "text": "Art is the echo of the soul speaking freely.", "author": "Kai Flow" },
  { "text": "Don’t chase perfection — chase expression.", "author": "Luna Craft" },
  { "text": "Creativity thrives in messy minds.", "author": "Ronan Brush" },
  { "text": "The dreamers build what logic never dares to.", "author": "Isla Spark" },
  { "text": "Every idea is a spark; protect it from the wind of doubt.", "author": "Theo Vision" },
  { "text": "Innovation begins where fear ends.", "author": "Clara Bold" },
  { "text": "The mind is a garden; creativity is its flower.", "author": "Leo Bloom" },
  { "text": "Originality is the courage to be misunderstood.", "author": "Maya Echo" },
  { "text": "Ideas grow where curiosity is nurtured.", "author": "Evan Quest" },
  { "text": "The artist sees what everyone else ignores.", "author": "Sophie Ink" },
  { "text": "Every mistake is a brushstroke in the masterpiece.", "author": "Finn Palette" },
  { "text": "Creativity is the rebellion against the ordinary.", "author": "Nina Flame" },
  { "text": "Let your imagination wander — it knows the way.", "author": "Miles Drift" },
  { "text": "Expression is the soul’s fingerprint on the world.", "author": "Lara Hue" },
  { "text": "Ideas are seeds; your mind is fertile soil.", "author": "Theo Sprout" },
  { "text": "Inspiration is everywhere; you just need to notice.", "author": "Ruby Gleam" },
  { "text": "The creative mind solves problems that don’t exist yet.", "author": "Ezra Flux" },
  { "text": "Art is not a hobby, it’s a lifeline.", "author": "Clara Hope" },
  { "text": "Creativity dances where routine fears to tread.", "author": "Leo Hart" },
  { "text": "Every thought has the potential to become a masterpiece.", "author": "Maya Shine" },
  { "text": "The imagination is limitless, your canvas should be too.", "author": "Evan Bliss" },
  { "text": "Innovation is curiosity in action.", "author": "Sophie Light" },
  { "text": "The artist’s mind is a universe waiting to be discovered.", "author": "Finn Merry" },
  { "text": "Creation begins where expectation ends.", "author": "Nina Glow" },
  { "text": "Original ideas often start as whispers in the mind.", "author": "Miles Cheer" },
  { "text": "Every brushstroke tells a story words cannot.", "author": "Lara Sun" },
  { "text": "Creativity is the playground of the bold.", "author": "Theo Bright" },
  { "text": "Art speaks when words fail.", "author": "Ruby Gleam" },
  { "text": "Innovation thrives on the edge of curiosity.", "author": "Ezra Glow" },
  { "text": "The mind is limitless; creativity sets it free.", "author": "Clara Hope" },
  { "text": "Every idea deserves a chance to bloom.", "author": "Leo Hart" },
  { "text": "Art is courage turned into color.", "author": "Maya Shine" },
  { "text": "Your imagination is a portal; step through it daily.", "author": "Evan Bliss" },
  { "text": "Creativity is the spark that ignites progress.", "author": "Sophie Light" },
  { "text": "The act of creating is the act of becoming.", "author": "Finn Merry" },
  { "text": "Original thought is a treasure worth protecting.", "author": "Nina Glow" },
  { "text": "Art transforms the ordinary into the extraordinary.", "author": "Miles Cheer" },
  { "text": "Innovation is born from curiosity, not instruction.", "author": "Lara Sun" },
  { "text": "Every creation is a mirror of the creator’s soul.", "author": "Theo Bright" },
  { "text": "Ideas are playful; let them roam.", "author": "Ruby Gleam" },
  { "text": "Creativity is seeing the invisible and making it visible.", "author": "Ezra Glow" },
  { "text": "Every invention begins as a daydream.", "author": "Clara Hope" },
  { "text": "The imagination is a playground for the brave.", "author": "Leo Hart" },
  { "text": "Artistic expression is a rebellion against mediocrity.", "author": "Maya Shine" },
  { "text": "Your ideas are priceless; treat them like treasures.", "author": "Evan Bliss" },
  { "text": "Innovation is the art of solving the unsolvable.", "author": "Sophie Light" },
  { "text": "The mind paints what the heart feels.", "author": "Finn Merry" },
  { "text": "Originality is born from relentless curiosity.", "author": "Nina Glow" },
  { "text": "Every creation starts with a spark of wonder.", "author": "Miles Cheer" },
  { "text": "The artist transforms the mundane into magical.", "author": "Lara Sun" },
  { "text": "Creativity is courage in colorful disguise.", "author": "Theo Bright" },
  { "text": "Imagination is a compass leading to new worlds.", "author": "Ruby Gleam" },
  { "text": "Art is freedom captured in form.", "author": "Ezra Glow" },
  { "text": "Every idea deserves a chance to dance.", "author": "Clara Hope" },
  { "text": "Innovation thrives where curiosity reigns.", "author": "Leo Hart" },
  { "text": "Creativity is a whisper of the soul asking to be heard.", "author": "Maya Shine" },
  { "text": "The act of creating is an act of courage.", "author": "Evan Bliss" },
  { "text": "Original ideas start with a single bold thought.", "author": "Sophie Light" },
  { "text": "Art reflects life with a twist of imagination.", "author": "Finn Merry" },
  { "text": "Creativity is the bridge between dreams and reality.", "author": "Nina Glow" },
  { "text": "Every invention begins as a question.", "author": "Miles Cheer" },
  { "text": "Your imagination is the birthplace of possibility.", "author": "Lara Sun" },
  { "text": "Creativity thrives where fear dares not enter.", "author": "Theo Bright" },
  { "text": "Art is the language of the infinite.", "author": "Ruby Gleam" },
  { "text": "Every idea has the power to change a life.", "author": "Ezra Glow" },
  { "text": "Innovation is curiosity turned into action.", "author": "Clara Hope" },
  { "text": "The creative soul leaves traces of wonder everywhere.", "author": "Leo Hart" },
  { "text": "Expression is the heartbeat of imagination.", "author": "Maya Shine" },
  { "text": "Creativity is the courage to see differently.", "author": "Evan Bliss" },
  { "text": "Every brushstroke is a journey into the mind.", "author": "Sophie Light" },
  { "text": "Artistry begins where certainty ends.", "author": "Finn Merry" },
  { "text": "Original ideas are gifts to the world.", "author": "Nina Glow" },
  { "text": "Creativity is the soul speaking through action.", "author": "Miles Cheer" },
  { "text": "Innovation begins when imagination meets courage.", "author": "Lara Sun" },
  { "text": "Your mind is a playground; let creativity play.", "author": "Theo Bright" },
  { "text": "Art is the soul’s dialogue with the universe.", "author": "Ruby Gleam" },
  { "text": "Every thought is a potential masterpiece.", "author": "Ezra Glow" },
  { "text": "Creativity turns chaos into beauty.", "author": "Clara Hope" },
  { "text": "Imagination is a journey, not a destination.", "author": "Leo Hart" },
  { "text": "Originality blooms when you dare to be different.", "author": "Maya Shine" },
  { "text": "Art transforms emotion into experience.", "author": "Evan Bliss" },
  { "text": "Creativity is seeing possibilities where others see problems.", "author": "Sophie Light" },
  { "text": "Every invention starts as a spark of curiosity.", "author": "Finn Merry" },
  { "text": "Your ideas are the seeds of a new world.", "author": "Nina Glow" },
  { "text": "Creativity is freedom wrapped in thought.", "author": "Miles Cheer" },
  { "text": "Innovation is the child of imagination.", "author": "Lara Sun" },
  { "text": "Art is where heart and mind converse.", "author": "Theo Bright" },
  { "text": "Every dream holds the blueprint of creation.", "author": "Ruby Gleam" },
  { "text": "Creativity is the soul’s answer to life’s questions.", "author": "Ezra Glow" }
],

"existential": [
  { "text": "Stars can’t shine without the weight of darkness.", "author": "Orion Vale" },
  { "text": "You are both a moment and an eternity.", "author": "Lyra Moon" },
  { "text": "Life doesn’t owe meaning — we create it.", "author": "Soren Night" },
  { "text": "Even the moon has phases and still shines.", "author": "Elara Dusk" },
  { "text": "The unknown is just tomorrow in disguise.", "author": "Kael Shadow" },
  { "text": "You are a universe pretending to be a person.", "author": "Nova Sky" },
  { "text": "Death teaches us the urgency of living.", "author": "Cassian Dark" },
  { "text": "In the end, we return to the silence we began with.", "author": "Selene Whisper" },
  { "text": "The night sky reminds us we’re small yet infinite.", "author": "Orin Star" },
  { "text": "Existence is poetry written in light and time.", "author": "Lyric Void" },
  { "text": "We are all travelers in the corridors of time.", "author": "Eris Faye" },
  { "text": "Life’s meaning is found between questions, not answers.", "author": "Alaric Wren" },
  { "text": "The present is all we truly hold.", "author": "Iris Vale" },
  { "text": "Consciousness is a lighthouse in the storm of existence.", "author": "Theo Lume" },
  { "text": "Every life is a single brushstroke on the canvas of eternity.", "author": "Nora Ash" },
  { "text": "We are fragments searching for the whole.", "author": "Ronan Shade" },
  { "text": "Time is a river; we are its fleeting reflections.", "author": "Selah Dawn" },
  { "text": "The absurdity of life is the stage for its beauty.", "author": "Kaelen Drift" },
  { "text": "We wander through meaning, discovering it in moments.", "author": "Liora Moon" },
  { "text": "The weight of existence is lightened by awareness.", "author": "Caius Star" },
  { "text": "Life whispers; only those who listen hear.", "author": "Vera Nyx" },
  { "text": "The horizon is endless because so is possibility.", "author": "Orion Vale" },
  { "text": "We are stardust given the gift of consciousness.", "author": "Lyra Moon" },
  { "text": "To exist is to be both seen and unseen.", "author": "Soren Night" },
  { "text": "Silence holds the weight of all unsaid truths.", "author": "Elara Dusk" },
  { "text": "Every choice shapes a shadow of eternity.", "author": "Kael Shadow" },
  { "text": "We are echoes in the canyon of existence.", "author": "Nova Sky" },
  { "text": "Life is fragile; its impermanence gives it depth.", "author": "Cassian Dark" },
  { "text": "Even in chaos, patterns of meaning emerge.", "author": "Selene Whisper" },
  { "text": "The cosmos reflects what we cannot see within.", "author": "Orin Star" },
  { "text": "We are strangers to ourselves and the world alike.", "author": "Lyric Void" },
  { "text": "Existence is a question wrapped in silence.", "author": "Eris Faye" },
  { "text": "Time devours all, yet leaves lessons behind.", "author": "Alaric Wren" },
  { "text": "Life’s fragility is the canvas of its beauty.", "author": "Iris Vale" },
  { "text": "Consciousness is the spark that lights the void.", "author": "Theo Lume" },
  { "text": "Every soul is a story the universe tells itself.", "author": "Nora Ash" },
  { "text": "We are the dream of the cosmos, briefly awake.", "author": "Ronan Shade" },
  { "text": "Time flows, yet we cling to the illusion of permanence.", "author": "Selah Dawn" },
  { "text": "The absurd is the shadow of deeper truths.", "author": "Kaelen Drift" },
  { "text": "To live is to oscillate between wonder and despair.", "author": "Liora Moon" },
  { "text": "Awareness transforms existence into understanding.", "author": "Caius Star" },
  { "text": "The moment is eternal in its fleetingness.", "author": "Vera Nyx" },
  { "text": "The universe is silent, yet it speaks in all things.", "author": "Orion Vale" },
  { "text": "We are the sum of our choices, fleeting and infinite.", "author": "Lyra Moon" },
  { "text": "Existence is a dialogue between chaos and order.", "author": "Soren Night" },
  { "text": "Life’s essence is felt in the spaces between events.", "author": "Elara Dusk" },
  { "text": "We are brief sparks in a boundless dark.", "author": "Kael Shadow" },
  { "text": "To be conscious is to carry both awe and sorrow.", "author": "Nova Sky" },
  { "text": "Mortality gives life its urgent poetry.", "author": "Cassian Dark" },
  { "text": "The journey is the question; living is the answer.", "author": "Selene Whisper" },
  { "text": "We are the question the universe cannot answer alone.", "author": "Orin Star" },
  { "text": "Existence is woven from uncertainty and courage.", "author": "Lyric Void" },
  { "text": "Time is both a cage and a gift.", "author": "Eris Faye" },
  { "text": "Life is luminous only because it fades.", "author": "Alaric Wren" },
  { "text": "Awareness is the mirror reflecting all that we are.", "author": "Iris Vale" },
  { "text": "The void is not empty; it is waiting for consciousness.", "author": "Theo Lume" },
  { "text": "Every heartbeat is a tiny rebellion against nothingness.", "author": "Nora Ash" },
  { "text": "We are fragments of starlight in the dark.", "author": "Ronan Shade" },
  { "text": "The absurdity of life makes it profoundly human.", "author": "Selah Dawn" },
  { "text": "Existence whispers truths only silence can hear.", "author": "Kaelen Drift" },
  { "text": "Life is both a question and an answer simultaneously.", "author": "Liora Moon" },
  { "text": "Awareness is the lighthouse guiding us through chaos.", "author": "Caius Star" },
  { "text": "Each moment carries the weight of eternity.", "author": "Vera Nyx" },
  { "text": "The cosmos is indifferent, yet we find meaning.", "author": "Orion Vale" },
  { "text": "We are both fleeting shadows and infinite light.", "author": "Lyra Moon" },
  { "text": "Consciousness is a spark illuminating the dark unknown.", "author": "Soren Night" },
  { "text": "To live is to create order from the absurd.", "author": "Elara Dusk" },
  { "text": "Mortality is the lens through which life gains focus.", "author": "Kael Shadow" },
  { "text": "The unknown is not to be feared but explored.", "author": "Nova Sky" },
  { "text": "Time dissolves all, yet meaning persists in moments.", "author": "Cassian Dark" },
  { "text": "Existence is a story told by consciousness itself.", "author": "Selene Whisper" },
  { "text": "The night reminds us of the vastness within us.", "author": "Orin Star" },
  { "text": "We are sparks of eternity temporarily awake.", "author": "Lyric Void" },
  { "text": "Life is fragile; yet its fragility makes it precious.", "author": "Eris Faye" },
  { "text": "The absurd is the doorway to profound insight.", "author": "Alaric Wren" },
  { "text": "Each breath is a defiance against the void.", "author": "Iris Vale" },
  { "text": "Consciousness is the echo of the universe in us.", "author": "Theo Lume" },
  { "text": "We are travelers navigating the maze of meaning.", "author": "Nora Ash" },
  { "text": "Life exists because we dare to notice it.", "author": "Ronan Shade" },
  { "text": "The moment is eternal if we choose to witness it.", "author": "Selah Dawn" },
  { "text": "Time is a circle within which we dance fleetingly.", "author": "Kaelen Drift" },
  { "text": "Existence humbles those who seek control over it.", "author": "Liora Moon" },
  { "text": "The cosmos reflects the questions we carry.", "author": "Caius Star" },
  { "text": "We are both insignificant and essential simultaneously.", "author": "Vera Nyx" },
  { "text": "Life is a canvas painted with the brush of impermanence.", "author": "Orion Vale" },
  { "text": "Consciousness illuminates the shadows of nothingness.", "author": "Lyra Moon" },
  { "text": "To exist is to oscillate between doubt and wonder.", "author": "Soren Night" },
  { "text": "The universe is vast, but so is the human heart.", "author": "Elara Dusk" },
  { "text": "Mortality gives urgency to our fleeting joys.", "author": "Kael Shadow" },
  { "text": "Existence is a puzzle with pieces shaped by experience.", "author": "Nova Sky" },
  { "text": "Every moment is both ordinary and eternal.", "author": "Cassian Dark" },
  { "text": "Awareness is the gift that transforms the mundane into profound.", "author": "Selene Whisper" },
  { "text": "The void is patient, yet we insist on filling it with meaning.", "author": "Orin Star" }
],
"growth": [
  { "text": "Don’t shrink to fit rooms you’ve outgrown.", "author": "Aurora Vale" },
  { "text": "You owe yourself the love you give so freely.", "author": "Caius Ember" },
  { "text": "Confidence is quiet — insecurity is loud.", "author": "Lyra Dawn" },
  { "text": "Fear fades when purpose speaks louder.", "author": "Orion Vale" },
  { "text": "Glow from within and watch the world reflect it.", "author": "Selene Faye" },
  { "text": "Be bold enough to be disliked for your authenticity.", "author": "Nova Star" },
  { "text": "Courage doesn’t roar; it whispers 'try again.'", "author": "Eris Nyx" },
  { "text": "You can’t bloom in soil that doubts your roots.", "author": "Kael Shade" },
  { "text": "Growth begins where comfort ends.", "author": "Vera Ash" },
  { "text": "Keep evolving — even your best self can be better.", "author": "Ronan Drift" },
  { "text": "Change is the pulse of progress.", "author": "Liora Moon" },
  { "text": "Every step forward is a victory over yesterday.", "author": "Caius Ember" },
  { "text": "Your potential is waiting beyond your fears.", "author": "Aurora Vale" },
  { "text": "Small shifts create monumental change over time.", "author": "Orion Vale" },
  { "text": "Let go of what limits your growth.", "author": "Selene Faye" },
  { "text": "Progress is messy, but it is proof of life.", "author": "Lyra Dawn" },
  { "text": "You are a work in progress, not a finished product.", "author": "Nova Star" },
  { "text": "Strength grows in the cracks of adversity.", "author": "Eris Nyx" },
  { "text": "Every ending is a chance to begin anew.", "author": "Kael Shade" },
  { "text": "Embrace discomfort; it is the fertilizer of growth.", "author": "Vera Ash" },
  { "text": "Patience plants seeds that persistence nurtures.", "author": "Ronan Drift" },
  { "text": "Let your curiosity lead the way.", "author": "Liora Moon" },
  { "text": "The tallest trees once weathered the strongest storms.", "author": "Aurora Vale" },
  { "text": "Adaptation is proof that you are alive.", "author": "Caius Ember" },
  { "text": "Your journey is unique — honor every step.", "author": "Orion Vale" },
  { "text": "Transformation starts with self-awareness.", "author": "Selene Faye" },
  { "text": "Your roots grow stronger with each challenge faced.", "author": "Lyra Dawn" },
  { "text": "Mistakes are the tuition for wisdom.", "author": "Nova Star" },
  { "text": "The brave embrace change even when afraid.", "author": "Eris Nyx" },
  { "text": "Growth is the art of becoming who you are.", "author": "Kael Shade" },
  { "text": "Nourish your mind, and your life will flourish.", "author": "Vera Ash" },
  { "text": "Success blooms from resilience, not luck.", "author": "Ronan Drift" },
  { "text": "Your limits exist only where you accept them.", "author": "Liora Moon" },
  { "text": "The journey of growth never truly ends.", "author": "Aurora Vale" },
  { "text": "Embrace the lessons hidden in failures.", "author": "Caius Ember" },
  { "text": "Strength is built quietly, one choice at a time.", "author": "Orion Vale" },
  { "text": "The seeds of growth often start in discomfort.", "author": "Selene Faye" },
  { "text": "You are capable of more than you realize.", "author": "Lyra Dawn" },
  { "text": "Change your thoughts, and your world will follow.", "author": "Nova Star" },
  { "text": "Resilience is the shadow of persistence.", "author": "Eris Nyx" },
  { "text": "The future favors those who prepare today.", "author": "Kael Shade" },
  { "text": "Your potential is a forest waiting to be explored.", "author": "Vera Ash" },
  { "text": "Progress isn’t linear, but it is certain.", "author": "Ronan Drift" },
  { "text": "Every challenge is a stepping stone, not a wall.", "author": "Liora Moon" },
  { "text": "Growth thrives on consistent effort, not occasional bursts.", "author": "Aurora Vale" },
  { "text": "Be patient with yourself; evolution takes time.", "author": "Caius Ember" },
  { "text": "Your best self is created, not discovered.", "author": "Orion Vale" },
  { "text": "Courage is choosing growth over comfort.", "author": "Selene Faye" },
  { "text": "The strongest roots grow in stormy soil.", "author": "Lyra Dawn" },
  { "text": "Small victories accumulate into monumental change.", "author": "Nova Star" },
  { "text": "Every effort counts, even when unseen.", "author": "Eris Nyx" },
  { "text": "Change is inevitable; growth is intentional.", "author": "Kael Shade" },
  { "text": "Your journey is a garden — tend it with care.", "author": "Vera Ash" },
  { "text": "Adversity is the forge of character.", "author": "Ronan Drift" },
  { "text": "The pursuit of growth is the essence of living.", "author": "Liora Moon" },
  { "text": "Let your failures be your compass, not your chains.", "author": "Aurora Vale" },
  { "text": "The strongest wings grow against the wind.", "author": "Caius Ember" },
  { "text": "Every step forward is a revolution against stagnation.", "author": "Orion Vale" },
  { "text": "Growth requires courage to leave comfort behind.", "author": "Selene Faye" },
  { "text": "Your evolution is your gift to the world.", "author": "Lyra Dawn" },
  { "text": "Learn, unlearn, and relearn — growth is cyclical.", "author": "Nova Star" },
  { "text": "The mountains of life build the strongest climbers.", "author": "Eris Nyx" },
  { "text": "Persistence turns dreams into reality.", "author": "Kael Shade" },
  { "text": "Your inner garden blooms with mindful attention.", "author": "Vera Ash" },
  { "text": "The path to growth is paved with challenges.", "author": "Ronan Drift" },
  { "text": "Let ambition guide you, but let values anchor you.", "author": "Liora Moon" },
  { "text": "True growth balances patience with action.", "author": "Aurora Vale" },
  { "text": "Growth is not an event, but a lifelong process.", "author": "Caius Ember" },
  { "text": "The brave transform obstacles into opportunities.", "author": "Orion Vale" },
  { "text": "Your roots anchor you; your dreams lift you.", "author": "Selene Faye" },
  { "text": "Resilience is the quiet backbone of progress.", "author": "Lyra Dawn" },
  { "text": "Change is the brushstroke of life on the canvas of self.", "author": "Nova Star" },
  { "text": "The journey toward growth reveals who you truly are.", "author": "Eris Nyx" },
  { "text": "Every challenge is a mirror reflecting your potential.", "author": "Kael Shade" },
  { "text": "Growth blooms in the soil of self-reflection.", "author": "Vera Ash" },
  { "text": "Each day is a chance to become more of yourself.", "author": "Ronan Drift" },
  { "text": "Persistence waters the seeds of transformation.", "author": "Liora Moon" },
  { "text": "Strength is cultivated through consistent effort.", "author": "Aurora Vale" },
  { "text": "Growth requires embracing both light and shadow.", "author": "Caius Ember" },
  { "text": "Your evolution is proof of your resilience.", "author": "Orion Vale" },
  { "text": "Every moment is a step on the ladder of growth.", "author": "Selene Faye" },
  { "text": "Challenges are invitations to expand your limits.", "author": "Lyra Dawn" },
  { "text": "Your life is your greatest work of art — keep refining it.", "author": "Nova Star" },
  { "text": "Adaptability is the signature of a growing soul.", "author": "Eris Nyx" },
  { "text": "The strongest roots weather the fiercest storms.", "author": "Kael Shade" },
  { "text": "Growth begins when you embrace uncertainty.", "author": "Vera Ash" },
  { "text": "Every sunrise brings a new opportunity to evolve.", "author": "Ronan Drift" },
  { "text": "Your potential is unlocked through persistence.", "author": "Liora Moon" },
  { "text": "True growth requires honesty with oneself.", "author": "Aurora Vale" },
  { "text": "Let your challenges be the fertilizer of your growth.", "author": "Caius Ember" },
  { "text": "Strength comes from embracing what you once feared.", "author": "Orion Vale" },
  { "text": "Your journey is unique — honor every step forward.", "author": "Selene Faye" },
  { "text": "Growth is a reflection of the choices you dare to make.", "author": "Lyra Dawn" },
  { "text": "The greatest progress occurs when comfort ends.", "author": "Nova Star" },
  { "text": "Every effort, no matter how small, contributes to transformation.", "author": "Eris Nyx" },
  { "text": "Your evolution is a testament to your courage.", "author": "Kael Shade" },
  { "text": "Growth is nurtured by persistence, patience, and self-belief.", "author": "Vera Ash" },
  { "text": "Embrace the process; it shapes the outcome.", "author": "Ronan Drift" },
  { "text": "Every step into discomfort is a step toward growth.", "author": "Liora Moon" }
]


  }}